{
    'name': 'Master Commission: Profit Sharing & Liquidations',
    'version': '18.0.1.0.0',
    'category': 'Sales/Sales',
    'summary': 'Automatically distribute profit margins from sales orders among registered partners.',
    'author': 'JDDM',
    'depends': ['sale_management', 'base', 'account'],
    'data': [
        'security/commission_security.xml',
        'security/ir.model.access.csv',
        'views/res_users_views.xml',
        'views/master_commission_record_views.xml',
        'views/res_config_settings_views.xml',
        'views/sale_order_views.xml',
        'views/product_template_views.xml',
        'views/master_commission_liquidation_views.xml',
        'views/commission_menus.xml',
    ],
    'images': ['static/description/banner.png', 'static/description/icon.png'],
    'price': 120.00,
    'currency': 'USD',
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
